services:
  backend:
    build:
      context: ./hydroalert-backend
    container_name: mern-backend
    restart: always
    ports:
      - "5000:5000"  # This exposes port 5000 to the outside world
    env_file:
      - ./hydroalert-backend/.env
    environment:
      - TELEGRAM_CHAT_ID=-1003822424705
      - MONGO_URI=mongodb://mongo:27017/flood_alert_db
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    depends_on:
      - mongo
      - redis
    volumes:
      - uploads_data:/app/uploads
    networks:
      - hydroalert-network
  
  frontend:
    build:
      context: ./hydroalert-frontend
    container_name: mern-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - hydroalert-network

  mongo:
    image: mongo:7
    container_name: hydroalert-mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - hydroalert-network
    
  redis:
    image: redis:7-alpine
    container_name: hydroalert-redis
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    networks:
      - hydroalert-network

networks:
  hydroalert-network:
    driver: bridge

volumes:
  mongo_data:
  redis_data:
  uploads_data:
