services:
  backend:
    build:
      context: ./hydroalert-backend
    container_name: mern-backend
    restart: always
    ports:
      - "5000:5000"  # This exposes port 5000 to the outside world
    env_file:
      - ./hydroalert-backend/.env
    environment:
      - TELEGRAM_CHAT_ID=-1003822424705
      - MONGO_URI=mongodb://mongo:27017/flood_alert_db
    depends_on:
      - mongo
    volumes:
      - uploads_data:/app/uploads

  mongo:
    image: mongo:7
    container_name: hydroalert-mongo
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  uploads_data:
