services:
  backend:
    build:
      context: ./hydroalert-backend
    container_name: mern-backend
    restart: always
    ports:
      - "127.0.0.1:5000:5000"  # This exposes port 5000 to the outside world
    env_file:
      - ./hydroalert-backend/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/flood_alert_db
    depends_on:
      - mongo

  # frontend:
  #   build:
  #     context: ./hydroalert-frontend
  #   container_name: mern-frontend
  #   restart: always
  #   ports:
  #     - "3000:80"
  #   env_file:
  #     - ./hydroalert-frontend/.env
  #   depends_on:
  #     - backend

  mongo:
    image: mongo:7
    container_name: hydroalert-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
